---
apiVesrion: apps/v1
kind: Deployment
metadta:
  name: flm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template: 
    metadata:
       labels:
          app: swiggy
  spec:
    containers:
      - name: con1
        image: shaikmustafa/paytm:movie
        ports:
         - containerPort: 80
