---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm
spec:
  replicas: 4
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont1
          image: mvvsbalakumar/tetris:v2
          ports:
          - containerPort: 3000
